use super::*;
use event_loop_control::EventLoopDirective;

pub(super) struct HeartbeatTickContext<'a> {
    pub(super) mode: &'a NodeMode,
    pub(super) queue: &'a Arc<TaskQueue>,
    pub(super) heartbeat: &'a Arc<HeartbeatService>,
    pub(super) pool: &'a Arc<WorkerPool>,
    pub(super) metrics: &'a Arc<RwLock<NodeMetrics>>,
    pub(super) peer_tracker: &'a mut PeerTracker,
    pub(super) direct_peers_count: usize,
    pub(super) rate_limiter: &'a mut RateLimiter,
    pub(super) swarm: &'a mut Swarm<IamineBehaviour>,
    pub(super) peer_id: PeerId,
    pub(super) capabilities: &'a WorkerCapabilities,
    pub(super) validated_advertised_models: &'a [String],
    pub(super) benchmark: Option<&'a NodeBenchmark>,
    pub(super) node_caps: &'a ModelNodeCapabilities,
    pub(super) worker_slots: usize,
    pub(super) topology: &'a SharedNetworkTopology,
    pub(super) registry: &'a SharedNodeRegistry,
    pub(super) resource_policy: &'a ResourcePolicy,
    pub(super) node_identity: &'a NodeIdentity,
    pub(super) worker_port: u16,
    pub(super) infer_runtime: &'a mut InferRuntimeState,
    pub(super) model_storage: &'a ModelStorage,
    pub(super) pubsub_topics: &'a PubsubTopicTracker,
    pub(super) client_state: &'a mut ClientRuntimeState,
    pub(super) debug_flags: DebugFlags,
    pub(super) task_manager: &'a Arc<TaskManager>,
}

pub(super) async fn handle_heartbeat_tick(
    ctx: HeartbeatTickContext<'_>,
) -> Result<EventLoopDirective, Box<dyn Error>> {
    let HeartbeatTickContext {
        mode,
        queue,
        heartbeat,
        pool,
        metrics,
        peer_tracker,
        direct_peers_count,
        rate_limiter,
        swarm,
        peer_id,
        capabilities,
        validated_advertised_models,
        benchmark,
        node_caps,
        worker_slots,
        topology,
        registry,
        resource_policy,
        node_identity,
        worker_port,
        infer_runtime,
        model_storage,
        pubsub_topics,
        client_state,
        debug_flags,
        task_manager,
    } = ctx;

    handle_worker_heartbeat_tick(WorkerHeartbeatContext {
        mode,
        queue,
        heartbeat,
        pool,
        metrics,
        peer_tracker,
        direct_peers_count,
        rate_limiter,
        swarm,
        peer_id,
        capabilities,
        validated_advertised_models,
        benchmark,
        node_caps,
        worker_slots,
        topology,
        registry,
        resource_policy,
        node_identity,
        worker_port,
    })
    .await?;

    handle_distributed_infer_tick(DistributedInferTickContext {
        mode,
        infer_runtime,
        model_storage,
        topology,
        peer_id,
        registry,
        pubsub_topics,
        client_state,
        debug_flags,
        swarm,
        metrics,
        task_manager,
    })
    .await
}
